/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Mostrar;
import BackEnd.Querys;
import BackEnd.Conexion;
import BackEnd.GuardarSalidasObject;
import BackEnd.Deletes;
import BackEnd.Registros;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Uriel RD
 */
public class MostrarSalidasGuardadas extends javax.swing.JFrame {

    /**
     * Creates new form MostrarSalidasGuardadas
     */
    String nombre="";
    GuardarSalidasObject guardarSalidasObject=new GuardarSalidasObject();
    public MostrarSalidasGuardadas() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jLabel1.setText("Salidas de "+getnombrebyuser());
        Mostrar mostrar=new Mostrar();
        mostrar.MostrarSalidasGuardadas(jTable1,getIDbyUser());
    }
    public String getnombrebyuser(){
        Conexion conexion=new Conexion();
        Connection con=conexion.ConnectDB();
        TecnicoSesion tecnicoSesion=new TecnicoSesion();
        nombre=TecnicoProducto.texto;
        String[] vec=new String[50];
        String sql="select * from tecnico where usuario ='"
                +nombre+"';";  
        try {
            Statement st = (Statement)con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
            vec[0] = rs.getString("Nombre");
          }     
        }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
        }
        return vec[0];
    }
    public String getIDbyUser(){
        Conexion conexion=new Conexion();
        Connection con=conexion.ConnectDB();
        TecnicoSesion tecnicoSesion=new TecnicoSesion();
        nombre=TecnicoProducto.texto;
        String[] vec=new String[50];
        String sql="select * from tecnico where usuario ='"
                +nombre+"';";  
        try {
            Statement st = (Statement)con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
            vec[0] = rs.getString("idTecnico");
          }     
        }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
        }
        return vec[0];
    }
     public String getIDProductobyCode(String code){
        Conexion conexion=new Conexion();
        Connection con=conexion.ConnectDB();
        String[] vec=new String[50];
        String sql="select * from producto where barras ='"
                +code+"';";  
        try {
            Statement st = (Statement)con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
            vec[0] = rs.getString("idProducto");
          }     
        }catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
        }
        return vec[0];
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Salidas Guardadas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/istockphoto-861685600-170667a (Personalizado) (Personalizado) (1).jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int fila=jTable1.getSelectedRow();
     Registros registros= new Registros();
     Querys querys= new Querys();
      if(fila>=0){
        registros.RegistrarSalidaTecnico("0",guardarSalidasObject.getIdregistro(),guardarSalidasObject.getIdproducto(),getIDbyUser(),
               querys.getCantidadbyIDGuardarSalida(guardarSalidasObject.getIdregistro()),
               guardarSalidasObject.getFecha(),querys.getComentariobyIDGuardarSalida(guardarSalidasObject.getIdregistro()),
               jTable1);
      }
      else{
          JOptionPane.showMessageDialog(null,"Seleccione primero una fila");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     int seleccion=jTable1.rowAtPoint(evt.getPoint()); 
     guardarSalidasObject.setIdregistro(String.valueOf(jTable1.getValueAt(seleccion,0)));
     guardarSalidasObject.setIdproducto(getIDProductobyCode(String.valueOf(jTable1.getValueAt(seleccion,1))));
     guardarSalidasObject.setFecha(String.valueOf(jTable1.getValueAt(seleccion,6)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila=jTable1.getSelectedRow();
    Deletes deletes=new Deletes();
        if(fila>=0){ 
        String idtecnico=getIDbyUser();
        deletes.EliminarSalidasGuardadas(guardarSalidasObject.getIdregistro(),jTable1,idtecnico);
        }
        else{
          JOptionPane.showMessageDialog(null,"Seleccione primero una fila");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       TecnicoProducto tecnicoProducto= new TecnicoProducto();
       tecnicoProducto.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarSalidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarSalidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarSalidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarSalidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarSalidasGuardadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
